services:
  - type: web
    name: cnr-handy-services
    runtime: node
    plan: free
    buildCommand: npm ci --production=false && npm run build
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000